spring.application.name=log-consumer
server.port=8082

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=log-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.logmonitor.log_consumer.model.LogMessage

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logmonitor
spring.datasource.username=loguser
spring.datasource.password=logpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Explicitly set the MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# AI
# Add Gemini
spring.ai.vertex.ai.gemini.api-key=AIzaSyBxDmVkcYnfIJMOx2j1c4_nHavO_lA27z4
spring.ai.vertex.ai.gemini.chat.options.model=gemini-1.5-flash
